from django.urls import path

from server.application import api, views

urlpatterns = [
    path("login", views.login_page),
    path("admin/login", views.admin_login_page),
    path("signup", views.signup_page),
    path("logout", views.logout_page),
    path("api/v1/auth/signup", api.signup_api),
    path("api/v1/health", api.health),
    path("api/v1/frontend/bootstrap", api.frontend_bootstrap),
    path("api/v1/dashboard/summary", api.dashboard_summary),
    path("api/v1/projects", api.projects),
    path("api/v1/project-management", api.project_management_api),
    path("api/v1/researchers", api.researchers_api),
    path("api/v1/data-updates", api.data_updates_api),
    path("api/v1/final-download", api.final_download_api),
    path("api/v1/signatures", api.signature_api),
    path("api/v1/admin/teams", api.admin_teams_api),
    path("api/v1/admin/users", api.admin_users_api),
    path("api/v1/admin/tables", api.admin_tables_api),
    path("api/v1/admin/tables/<str:table_name>/truncate", api.admin_table_truncate_api),
    path("api/v1/research-notes", api.research_notes_api),
    path("api/v1/research-notes/<str:note_id>", api.research_note_detail_api),
    path("api/v1/research-notes/<str:note_id>/update", api.research_note_update_api),
    path("frontend/workflows", views.workflow_home_page),
    path("frontend/admin", views.admin_page),
    path("frontend/admin/dashboard", views.admin_dashboard_page),
    path("frontend/admin/teams", views.admin_teams_page),
    path("frontend/admin/users", views.admin_users_page),
    path("frontend/admin/tables", views.admin_tables_page),
    path("frontend/projects", views.project_management_page),
    path("frontend/projects/create", views.project_create_page),
    path("frontend/projects/<str:project_id>", views.project_detail_page),
    path("frontend/my-page", views.my_page),
    path("frontend/my-page/signature", views.update_my_signature),
    path("frontend/researchers", views.researchers_page),
    path("frontend/data-updates", views.data_updates_page),
    path("frontend/final-download", views.final_download_page),
    path("frontend/signatures", views.signature_page),
    path("frontend/research-notes", views.research_notes_page),
    path("frontend/research-notes/<str:note_id>", views.research_note_detail_page),
    path("frontend/research-notes/<str:note_id>/viewer", views.research_note_viewer_page),
]
