# Generated by Django 5.2.11 on 2026-02-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_app", "0009_alter_projectmember_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Researcher",
        ),
    ]
