# Generated by Django 5.2.11 on 2026-03-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_app", "0011_useraccount_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="role",
            field=models.CharField(
                choices=[("owner", "소유자"), ("admin", "관리자"), ("member", "일반")],
                default="member",
                max_length=20,
            ),
        ),
    ]
