# Generated by Django 5.2.11 on 2026-02-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_app", "0008_remove_projectmember_researcher"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together=set(),
        ),
    ]
