# Generated by Django 5.2.11 on 2026-02-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_app", "0010_delete_researcher"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
