# Generated by Django 5.2.11 on 2026-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_app", "0013_useraccount_requested_team_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="business_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
