# Generated by Django 5.2.11 on 2026-03-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_app", "0014_project_business_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectNoteCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=100)),
                (
                    "business_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "organization",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("manager", models.CharField(blank=True, default="", max_length=120)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("show_business_name", models.BooleanField(default=True)),
                ("show_title", models.BooleanField(default=True)),
                ("show_code", models.BooleanField(default=True)),
                ("show_org", models.BooleanField(default=True)),
                ("show_manager", models.BooleanField(default=True)),
                ("show_period", models.BooleanField(default=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_cover",
                        to="workflow_app.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
