from django.urls import path

from . import api, auth, web

urlpatterns = [
    path("login", auth.login_page),
    path("admin/login", auth.admin_login_page),
    path("signup", auth.signup_page),
    path("logout", auth.logout_page),
    path("api/v1/auth/signup", auth.signup_api),
    path("api/v1/health", api.health),
    path("api/v1/frontend/bootstrap", api.frontend_bootstrap),
    path("api/v1/dashboard/summary", api.dashboard_summary),
    path("api/v1/projects", api.projects),
    path("api/v1/project-management", api.project_management_api),
    path("api/v1/researchers", api.researchers_api),
    path("api/v1/data-updates", api.data_updates_api),
    path("api/v1/final-download", api.final_download_api),
    path("api/v1/signatures", api.signature_api),
    path("api/v1/admin/teams", api.admin_teams_api),
    path("api/v1/admin/users", api.admin_users_api),
    path("api/v1/admin/tables", api.admin_tables_api),
    path("api/v1/admin/tables/<str:table_name>/truncate", api.admin_table_truncate_api),
    path("api/v1/research-notes", api.research_notes_api),
    path("api/v1/research-notes/<str:note_id>", api.research_note_detail_api),
    path("api/v1/research-notes/<str:note_id>/update", api.research_note_update_api),
    path("frontend/workflows", web.workflow_home_page),
    path("frontend/admin", web.admin_page),
    path("frontend/admin/dashboard", web.admin_dashboard_page),
    path("frontend/admin/teams", web.admin_teams_page),
    path("frontend/admin/users", web.admin_users_page),
    path("frontend/admin/tables", web.admin_tables_page),
    path("frontend/projects", web.project_management_page),
    path("frontend/projects/create", web.project_create_page),
    path("frontend/projects/<str:project_id>", web.project_detail_page),
    path("frontend/my-page", web.my_page),
    path("frontend/my-page/signature", web.update_my_signature),
    path("frontend/researchers", web.researchers_page),
    path("frontend/data-updates", web.data_updates_page),
    path("frontend/final-download", web.final_download_page),
    path("frontend/signatures", web.signature_page),
    path("frontend/research-notes", web.research_notes_page),
    path("frontend/research-notes/<str:note_id>", web.research_note_detail_page),
    path("frontend/research-notes/<str:note_id>/viewer", web.research_note_viewer_page),
]
