export const routeCatalog = [
  { path: '/', source: 'legacy/client/workflow/home.html' },
  { path: '/auth/login', source: 'legacy/client/auth/login.html' },
  { path: '/auth/signup', source: 'legacy/client/auth/signup.html' },
  { path: '/auth/admin-login', source: 'legacy/client/auth/admin_login.html' },
  { path: '/projects', source: 'legacy/client/workflow/projects.html' },
  { path: '/projects/create', source: 'legacy/client/workflow/project_create.html' },
  { path: '/projects/:id', source: 'legacy/client/workflow/project_detail.html' },
  { path: '/researchers', source: 'legacy/client/workflow/researchers.html' },
  { path: '/projects/:id/researchers', source: 'legacy/client/workflow/project_researchers.html' },
  { path: '/my-page', source: 'legacy/client/workflow/my_page.html' },
  { path: '/data-updates', source: 'legacy/client/workflow/collaboration_integrations.html' },
  { path: '/integrations/github', source: 'legacy/client/workflow/github_integrations.html' },
  { path: '/signatures', source: 'legacy/client/workflow/signatures.html' },
  { path: '/admin', source: 'legacy/client/admin/admin.html' },
  { path: '/admin/dashboard', source: 'legacy/client/admin/dashboard.html' },
  { path: '/admin/users', source: 'legacy/client/admin/users.html' },
  { path: '/admin/teams', source: 'legacy/client/admin/teams.html' },
  { path: '/admin/tables', source: 'legacy/client/admin/tables.html' }
];
