export const routeCatalog = [
  { path: '/', title: '워크플로우 홈', source: 'client/workflow/home.html' },
  { path: '/auth/login', title: '로그인', source: 'client/auth/login.html' },
  { path: '/auth/signup', title: '회원가입', source: 'client/auth/signup.html' },
  { path: '/auth/admin-login', title: '관리자 로그인', source: 'client/auth/admin_login.html' },
  { path: '/projects', title: '프로젝트 목록', source: 'client/workflow/projects.html' },
  { path: '/projects/create', title: '프로젝트 생성', source: 'client/workflow/project_create.html' },
  { path: '/projects/:id', title: '프로젝트 상세', source: 'client/workflow/project_detail.html' },
  { path: '/projects/:id/research-notes', title: '프로젝트 연구노트', source: 'client/workflow/project_research_notes.html' },
  { path: '/projects/:id/research-notes/print', title: '프로젝트 연구노트 인쇄', source: 'client/workflow/project_research_notes_print.html' },
  { path: '/researchers', title: '연구자 목록', source: 'client/workflow/researchers.html' },
  { path: '/projects/:id/researchers', title: '프로젝트 참여 연구자', source: 'client/workflow/project_researchers.html' },
  { path: '/research-notes', title: '연구노트 목록', source: 'client/research_notes/list.html' },
  { path: '/research-notes/:id', title: '연구노트 상세', source: 'client/research_notes/detail.html' },
  { path: '/research-notes/:id/viewer', title: '연구노트 뷰어', source: 'client/research_notes/viewer.html' },
  { path: '/research-notes/:id/cover', title: '연구노트 커버', source: 'client/research_notes/cover.html' },
  { path: '/research-notes/:id/printable', title: '연구노트 인쇄', source: 'client/research_notes/printable.html' },
  { path: '/my-page', title: '마이페이지', source: 'client/workflow/my_page.html' },
  { path: '/data-updates', title: '활동 내역', source: 'client/workflow/collaboration_integrations.html' },
  { path: '/signatures', title: '서명 관리', source: 'client/workflow/signatures.html' },
  { path: '/integrations/github', title: 'GitHub 연동', source: 'client/workflow/github_integrations.html' },
  { path: '/final-download', title: '최종 다운로드', source: 'client/workflow/final_download.html' },
  { path: '/admin', title: '관리자 홈', source: 'client/admin/admin.html' },
  { path: '/admin/dashboard', title: '관리자 대시보드', source: 'client/admin/dashboard.html' },
  { path: '/admin/teams', title: '팀 관리', source: 'client/admin/teams.html' },
  { path: '/admin/users', title: '사용자 관리', source: 'client/admin/users.html' },
  { path: '/admin/tables', title: '테이블 점검', source: 'client/admin/tables.html' }
];
