export const routeCatalog = [
  { path: '/', backendPath: '/frontend/workflows' },
  { path: '/auth/login', backendPath: '/login' },
  { path: '/auth/signup', backendPath: '/signup' },
  { path: '/auth/admin-login', backendPath: '/admin/login' },
  { path: '/projects', backendPath: '/frontend/projects' },
  { path: '/projects/create', backendPath: '/frontend/projects/create' },
  { path: '/projects/:id', backendPath: ({ id }) => `/frontend/projects/${id}` },
  { path: '/projects/:id/research-notes', backendPath: ({ id }) => `/frontend/projects/${id}/research-notes` },
  { path: '/projects/:id/research-notes/print', backendPath: ({ id }) => `/frontend/projects/${id}/research-notes/print` },
  { path: '/researchers', backendPath: '/frontend/researchers' },
  { path: '/projects/:id/researchers', backendPath: ({ id }) => `/frontend/projects/${id}/researchers` },
  { path: '/research-notes', backendPath: '/frontend/research-notes' },
  { path: '/research-notes/:id', backendPath: ({ id }) => `/frontend/research-notes/${id}` },
  { path: '/my-page', backendPath: '/frontend/my-page' },
  { path: '/data-updates', backendPath: '/frontend/data-updates' },
  { path: '/signatures', backendPath: '/frontend/signatures' },
  { path: '/final-download', backendPath: '/frontend/final-download' },
  { path: '/admin', backendPath: '/frontend/admin' },
  { path: '/admin/dashboard', backendPath: '/frontend/admin/dashboard' },
  { path: '/admin/teams', backendPath: '/frontend/admin/teams' },
  { path: '/admin/users', backendPath: '/frontend/admin/users' },
  { path: '/admin/tables', backendPath: '/frontend/admin/tables' }
];
